#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

picom -b --config ~/.config/picom/picom.conf &
~/.config/lemonbar/lemonbarrc | lemonbar -p -g $(xwininfo -root | grep 'Width' | cut -c 10-)x40 &
alacritty -e bash -c 'profanity' &
sleep 0.1
alacritty -e bash -c 'vim ~/docs/omni.txt && newsboat -r && clear && neofetch && cal -mn3 && $SHELL' &
