#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if xrandr -q | grep -q 'DisplayPort-1 connected'; then
  bspc monitor eDP -d I II III IV V
  bspc monitor DisplayPort-1 -d VI VII VIII IX X
else
  bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

pulseaudio --start 2>/dev/null
picom -b --config ~/.config/picom/picom.conf &
~/.config/lemonbar/lemonbarrc | lemonbar -p -g $(($(xwininfo -root | grep 'Width' | cut -c10-)))x40 &
alacritty -e bash -c 'profanity' &
# this could be more thorough (as in the bashrc) but it's not really necessary unless you somehow have a zombie process that's survived X literally being killed, which seems impossible to me--but I may as well put this here anyway
until pgrep 'profanity'; do
  :
done
alacritty -e bash -c "neomutt; task list; cal -mn3; $SHELL" &
until pgrep "neomutt"; do
  :
done
alacritty -e bash -c "vim ~/docs/omni.txt; newsboat -r; clear; neofetch; $SHELL" &
